// apps/3-ssr/3-2-react-router-ssr/app/components/AppLayout.tsx
import { Anchor, AppShell, Burger, Group } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { IconHome, IconUsersGroup } from "@tabler/icons-react";
import { Link } from "react-router";

interface AppLayoutProps {
  children: React.ReactNode;
}

const links = [
  {
    icon: <IconHome size="1rem" />,
    color: "blue",
    label: "Home Feed",
    href: "/",
  },
  {
    icon: <IconUsersGroup size="1rem" />,
    color: "teal",
    label: "Users",
    href: "/users",
  },
];

export function AppLayout({ children }: AppLayoutProps) {
  const [opened, { toggle }] = useDisclosure();

  return (
    <AppShell
      header={{ height: 60 }}
      navbar={{ width: 200, breakpoint: "sm", collapsed: { mobile: !opened } }}
      padding="xl"
    >
      <AppShell.Header>
        <Group h="100%" px="md">
          <Burger opened={opened} onClick={toggle} size="sm" />
          React Router SSR (and React Query)
        </Group>
      </AppShell.Header>
      <AppShell.Navbar p="md">
        {links.map((link) => (
          <Anchor component={Link} key={link.label} to={link.href}>
            {link.label}
          </Anchor>
        ))}
      </AppShell.Navbar>
      <AppShell.Main mb="xl">{children}</AppShell.Main>
    </AppShell>
  );
}

// apps/5.1-sveltekit-ssr/src/lib/components/AppLayout.svelte
<script lang="ts">
	import { Navbar, NavBrand, NavLi, NavUl, NavHamburger } from 'flowbite-svelte';
	import { HomeOutline, UsersGroupOutline } from 'flowbite-svelte-icons';

	const links = [
		{ icon: HomeOutline, color: 'text-blue-500', label: 'Home Feed', href: '/' },
		{ icon: UsersGroupOutline, color: 'text-teal-500', label: 'Users', href: '/users' }
	];
</script>

<Navbar let:hidden let:toggle>
	<NavBrand href="/">
		<span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
			SvelteKit SSR (and Svelte Query)
		</span>
	</NavBrand>
	<NavHamburger on:click={toggle} />
	<NavUl {hidden}>
		{#each links as link}
			<NavLi href={link.href}>
				<svelte:component this={link.icon} class="{link.color} mr-2 h-4 w-4" />
				{link.label}
			</NavLi>
		{/each}
	</NavUl>
</Navbar>

<main class="container mx-auto mb-96 mt-4 px-4">
	<slot></slot>
</main>
