// apps/3-ssr/3-1-nextjs-ssr/src/pages/posts/[id].tsx
import { useCallback, useState } from "react";
import {
  ActionIcon,
  Alert,
  Box,
  Button,
  Card,
  Collapse,
  Flex,
  Loader,
  Skeleton,
  Stack,
  Text,
  Textarea,
  Title,
  Tooltip,
} from "@mantine/core";
import { IconAlertCircle, IconRefresh, IconTrash } from "@tabler/icons-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { IComment, IPost, IUser } from "../../api-types";
import Link from "next/link";
import { useParams } from "next/navigation";
import { GetServerSideProps } from "next";

//Load post and comments on server side for SEO
export const getServerSideProps: GetServerSideProps = async (context) => {
  const { id: postId } = context.params!;

  try {
    const [postResponse, commentsResponse] = await Promise.all([
      fetch(`http://localhost:3300/posts/${postId}`),
      fetch(`http://localhost:3300/posts/${postId}/comments`),
    ]);

    const [initialPost, initialComments] = await Promise.all([
      postResponse.json(),
      commentsResponse.json(),
    ]);

    return {
      props: {
        initialPost,
        initialComments,
        error: false,
      },
    };
  } catch (error) {
    console.error(error);

    return {
      props: {
        initialPost: null,
        error: true,
      },
    };
  }
};

interface IPostPageProps {
  initialPost: IPost;
  initialComments: IComment[];
  error: boolean;
}

export default function PostPage({
  initialPost,
  initialComments,
  error: pageError,
}: IPostPageProps) {
  const queryClient = useQueryClient();
  const { id: postId } = useParams();

  //load post - with initial data from server
  const {
    data: post,
    isLoading: isLoadingPost,
    isError: isErrorLoadingPosts,
  } = useQuery({
    initialData: initialPost,
    queryKey: [`/posts/${postId}`],
    queryFn: async () => {
      const response = await fetch(`http://localhost:3300/posts/${postId}`);
      return response.json() as Promise<IPost>;
    },
  });

  //load user - depends on user id from post
  const {
    data: user,
    isLoading: isLoadingUser,
    isError: isErrorLoadingUser,
  } = useQuery({
    enabled: !!post?.userId,
    queryKey: [`/users/${post?.userId}`],
    queryFn: async () => {
      const response = await fetch(
        `http://localhost:3300/users/${post?.userId}`,
      );
      return response.json() as Promise<IUser>;
    },
  });

  //load comments - with initial data from server
  const {
    data: comments,
    isLoading: isLoadingComments,
    isFetching: isFetchingComments,
    isError: isErrorLoadingComments,
    refetch: refetchComments,
  } = useQuery({
    initialData: initialComments,
    queryKey: [`/posts/${postId}/comments`],
    queryFn: async () => {
      const response = await fetch(
        `http://localhost:3300/posts/${postId}/comments`,
      );
      return response.json() as Promise<IComment[]>;
    },
    refetchInterval: 10000, // 10 seconds
  });

  //delete comment, refresh comments after delete
  const {
    mutate: deleteComment,
    isPending: isDeletingComment,
    context: deletingCommentContext,
  } = useMutation({
    mutationFn: async (commentId: number) => {
      const response = await fetch(
        `http://localhost:3300/comments/${commentId}`,
        {
          method: "DELETE",
        },
      );
      return response.json() as Promise<IComment>;
    },
    //record which comment is being deleted so we can give it lower opacity
    onMutate: async (commentId) => ({ commentId }),
    onError: (err, commentId) => {
      console.error(
        `Error deleting comment ${commentId}. Rolling UI back`,
        err,
      );
      alert("Error deleting comment");
    },
    onSettled: () => {
      queryClient.invalidateQueries({
        queryKey: [`/posts/${postId}/comments`],
      }); //refresh comments
    },
  });

  const handleDeleteComment = useCallback(
    (commentId: number) => {
      deleteComment(commentId);
    },
    [deleteComment],
  );

  // Post new comment - with optimistic updates!
  const [commentText, setCommentText] = useState("");

  const { mutate: postComment, isPending: isPostingComment } = useMutation({
    mutationFn: async (comment: Omit<IComment, "id">) => {
      const response = await fetch(`http://localhost:3300/comments`, {
        method: "POST",
        body: JSON.stringify(comment),
        headers: {
          "Content-type": "application/json; charset=UTF-8",
        },
      });
      return response.json() as Promise<IComment>;
    },
    //optimistic client-side update
    onMutate: async (newComment) => {
      await queryClient.cancelQueries({
        queryKey: [`/posts/${postId}/comments`],
      });

      // Snapshot the previous value
      const previousComments = queryClient.getQueryData([
        "comments",
        newComment.postId.toString(),
      ]);

      // Optimistically update to the new value
      queryClient.setQueryData(
        [`/posts/${postId}/comments`],
        (oldComments: any) => [...oldComments, newComment],
      );

      // Return a context object with the snapshot value
      return { previousComments };
    },
    // If the mutation fails,
    // use the context returned from onMutate to roll back
    onError: (err, _newComment, context) => {
      queryClient.setQueryData(
        [`/posts/${postId}/comments`],
        context?.previousComments,
      );
      console.error("Error posting comment. Rolling UI back", err);
    },
    onSuccess: () => {
      setCommentText(""); //clear comment text
    },
    // Always refetch after error or success:
    onSettled: () => {
      queryClient.invalidateQueries({
        queryKey: [`/posts/${postId}/comments`],
      });
    },
  });

  const handleSubmitComment = useCallback(async () => {
    const newComment: Omit<IComment, "id"> = {
      body: commentText,
      email: "user@mailinator.com",
      name: "User",
      postId: Number(postId),
    };
    postComment(newComment);
  }, [commentText, postId, postComment]);

  if (pageError) {
    return (
      <Alert icon={<IconAlertCircle size="1rem" />} title="Bummer!" color="red">
        There was an error loading this post
      </Alert>
    );
  }

  return (
    <Stack>
      <Box>
        {isErrorLoadingPosts || isErrorLoadingUser ? (
          <Alert
            icon={<IconAlertCircle size="1rem" />}
            title="Bummer!"
            color="red"
          >
            There was an error loading this post
          </Alert>
        ) : !post || isLoadingPost || isLoadingUser ? (
          <>
            <Skeleton animate height="20px" width="50%" mb="md" />
            <Skeleton animate height="40px" width="100%" mb="md" />
          </>
        ) : (
          <>
            <Title order={1}>Post: {post?.id}</Title>
            <Title order={2}>{post?.title}</Title>
            <Title order={3}>
              By:{" "}
              <Link
                href={`/users/${user?.id}`}
                style={{ textDecoration: "none" }}
              >
                {user?.name}
              </Link>
            </Title>
            <Text my="lg">
              {post.body}. {post.body}. {post.body}. {post.body}. {post.body}.
            </Text>
          </>
        )}
      </Box>
      <Flex justify="space-between" align="center">
        <Title mt="lg" order={3}>
          Comments on this Post
        </Title>
        <Tooltip withArrow label="Refresh Comments">
          <ActionIcon variant="subtle" onClick={() => refetchComments()}>
            <IconRefresh />
          </ActionIcon>
        </Tooltip>
      </Flex>
      <Flex w="100%" justify="center" mih="2rem">
        <Collapse in={isFetchingComments || isDeletingComment}>
          <Loader />
        </Collapse>
      </Flex>
      <Stack gap="xl">
        {isErrorLoadingComments ? (
          <Alert
            icon={<IconAlertCircle size="1rem" />}
            title="Bummer!"
            color="red"
          >
            There was an error loading comments for this post
          </Alert>
        ) : isLoadingComments ? (
          [...Array(5)].map((_, index) => (
            <Card withBorder key={index}>
              <Skeleton animate height="20px" width="25%" mb="md" />
              <Skeleton animate height="15px" width="33%" mb="md" />
              <Skeleton animate height="40px" width="100%" mb="md" />
            </Card>
          ))
        ) : (
          comments?.map((comment) => (
            <Card
              withBorder
              opacity={
                isDeletingComment &&
                deletingCommentContext?.commentId === comment.id
                  ? 0.5
                  : 1
              }
              key={comment.id + comment.email}
            >
              {comment.email === "user@mailinator.com" && (
                <ActionIcon
                  color="red"
                  pos="absolute"
                  right={10}
                  top={10}
                  variant="subtle"
                  onClick={() => handleDeleteComment(comment.id)}
                >
                  <IconTrash />
                </ActionIcon>
              )}

              <Title order={4}>{comment.name}</Title>
              <Title order={5}>{comment.email}</Title>
              <Text>{comment.body}</Text>
            </Card>
          ))
        )}
        <Textarea
          disabled={isPostingComment}
          label="Post a Comment"
          onChange={(e) => setCommentText(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              handleSubmitComment();
            }
          }}
          value={commentText}
        />
        <Button
          disabled={isPostingComment || commentText.length === 0}
          leftSection={
            isPostingComment ? (
              <Loader variant="oval" color="white" size="xs" />
            ) : null
          }
          onClick={handleSubmitComment}
        >
          Post Comment
        </Button>
      </Stack>
    </Stack>
  );
}

// apps/3-ssr/3-3-sveltekit-ssr/src/routes/posts/[id]/+page.svelte
<script lang="ts">
	import { Alert, Button, Card, Textarea } from 'flowbite-svelte';
	import { createQuery, createMutation, useQueryClient } from '@tanstack/svelte-query';
	import type { PageData } from './$types';
	import type { IPost, IComment, IUser } from '$lib/api-types';

	export let data: PageData;
	let { initialPost, initialComments, error: pageError } = data;

	const queryClient = useQueryClient();
	let postId = initialPost?.id;
	let commentText = '';

	const postQuery = createQuery({
		queryKey: [`/posts/${postId}`],
		queryFn: async () => {
			const response = await fetch(`http://localhost:3300/posts/${postId}`);
			return response.json() as Promise<IPost>;
		},
		initialData: initialPost
	});

	const userQuery = createQuery({
		queryKey: [`/users/${$postQuery.data?.userId}`],
		queryFn: async () => {
			const response = await fetch(`http://localhost:3300/users/${$postQuery.data?.userId}`);
			return response.json() as Promise<IUser>;
		},
		enabled: !!$postQuery.data?.userId
	});

	const commentsQuery = createQuery({
		queryKey: [`/posts/${postId}/comments`],
		queryFn: async () => {
			const response = await fetch(`http://localhost:3300/posts/${postId}/comments`);
			return response.json() as Promise<IComment[]>;
		},
		initialData: initialComments,
		refetchInterval: 10000
	});

	const deleteCommentMutation = createMutation({
		mutationFn: async (commentId: number) => {
			const response = await fetch(`http://localhost:3300/comments/${commentId}`, {
				method: 'DELETE'
			});
			return response.json() as Promise<IComment>;
		},
		onSettled: () => {
			queryClient.invalidateQueries({ queryKey: [`/posts/${postId}/comments`] });
		}
	});

	const postCommentMutation = createMutation({
		mutationFn: async (comment: Omit<IComment, 'id'>) => {
			const response = await fetch(`http://localhost:3300/comments`, {
				method: 'POST',
				body: JSON.stringify(comment),
				headers: {
					'Content-type': 'application/json; charset=UTF-8'
				}
			});
			return response.json() as Promise<IComment>;
		},
		onMutate: async (newComment) => {
			await queryClient.cancelQueries({ queryKey: [`/posts/${postId}/comments`] });
			const previousComments = queryClient.getQueryData([`/posts/${postId}/comments`]);
			queryClient.setQueryData([`/posts/${postId}/comments`], (oldComments: any) => [
				...oldComments,
				newComment
			]);
			return { previousComments };
		},
		onError: (err, _newComment, context) => {
			queryClient.setQueryData([`/posts/${postId}/comments`], context?.previousComments);
			console.error('Error posting comment. Rolling UI back', err);
		},
		onSuccess: () => {
			commentText = '';
		},
		onSettled: () => {
			queryClient.invalidateQueries({ queryKey: [`/posts/${postId}/comments`] });
		}
	});

	function handleDeleteComment(commentId: number) {
		$deleteCommentMutation.mutate(commentId);
	}

	function handleSubmitComment() {
		if (!commentText || !postId) return;
		const newComment: Omit<IComment, 'id'> = {
			body: commentText,
			email: 'user@mailinator.com',
			name: 'User',
			postId: postId
		};
		$postCommentMutation.mutate(newComment);
	}
</script>

<div class="p-8">
	{#if pageError}
		<Alert color="red">
			<span class="font-medium">Bummer!</span>
			There was an error loading this post
		</Alert>
	{:else if $postQuery.isLoading || $userQuery.isLoading}
		<div class="animate-pulse">
			<div class="mb-4 h-4 w-1/2 rounded-full bg-gray-200"></div>
			<div class="mb-4 h-8 w-full rounded-full bg-gray-200"></div>
		</div>
	{:else if $postQuery.isError || $userQuery.isError}
		<Alert color="red">
			<span class="font-medium">Bummer!</span>
			There was an error loading this post
		</Alert>
	{:else if $postQuery.data}
		<h1 class="mb-2 text-3xl font-bold">Post: {$postQuery.data.id}</h1>
		<h2 class="mb-2 text-2xl font-semibold">{$postQuery.data.title}</h2>
		<h3 class="mb-4 text-xl">
			By:
			{#if $userQuery.isLoading}
				<span class="animate-pulse">Loading...</span>
			{:else if $userQuery.isError}
				<span class="text-red-500">Error loading user</span>
			{:else}
				<a href="/users/{$userQuery.data?.id}" class="text-blue-600 hover:underline"
					>{$userQuery.data?.name}</a
				>
			{/if}
		</h3>
		<p class="mb-8">{$postQuery.data.body}</p>

		<h3 class="mb-4 text-xl font-semibold">Comments on this Post</h3>

		<div class="mb-8 w-full space-y-4">
			{#if $commentsQuery.isLoading}
				<div class="animate-pulse">
					<div class="mb-4 h-4 w-1/2 rounded-full bg-gray-200"></div>
					<div class="mb-4 h-8 w-full rounded-full bg-gray-200"></div>
				</div>
			{:else if $commentsQuery.isError}
				<Alert color="red">
					<span class="font-medium">Bummer!</span>
					There was an error loading comments
				</Alert>
			{:else}
				{#each $commentsQuery.data as comment (comment.id)}
					<Card class="w-full" padding="none" size="xl">
						<div class="flex w-full items-start justify-between p-4">
							<div>
								<h4 class="font-semibold">{comment.name}</h4>
								<h5 class="text-sm text-gray-600">{comment.email}</h5>
							</div>
							{#if comment.email === 'user@mailinator.com'}
								<button
									class="text-red-500 hover:text-red-700"
									on:click={() => handleDeleteComment(comment.id)}
								>
									Delete
								</button>
							{/if}
						</div>
						<p class="mt-2 px-4 pb-4">{comment.body}</p>
					</Card>
				{/each}
			{/if}
		</div>

		<Textarea
			bind:value={commentText}
			label="Post a Comment"
			rows={4}
			class="mb-4"
			disabled={$postCommentMutation.isPending}
		/>
		<Button
			on:click={handleSubmitComment}
			disabled={$postCommentMutation.isPending || commentText.length === 0}
		>
			{#if $postCommentMutation.isPending}
				<svg class="mr-3 h-5 w-5 animate-spin" viewBox="0 0 24 24">
					<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"
					></circle>
					<path
						class="opacity-75"
						fill="currentColor"
						d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
					></path>
				</svg>
			{/if}
			Post Comment
		</Button>
	{/if}
</div>
