// apps/1-csr/1-8-vite-tanstack-router-file-based-routing/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { Card, Flex, Stack, Text, Title } from "@mantine/core";
import { Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { postsQueryOptions } from "../queries/posts";

export const Route = createFileRoute("/")({
  loader: ({ context: { queryClient } }) =>
    queryClient.ensureQueryData(postsQueryOptions),
  component: HomePage,
});

function HomePage() {
  const { data: posts } = useSuspenseQuery(postsQueryOptions);

  return (
    <Stack>
      <Title order={2}>Your Home Feed</Title>
      <Flex wrap="wrap" gap="1rem">
        {posts.map((post) => (
          <Link
            key={post.id}
            to="/posts/$id"
            params={{ id: post.id.toString() }}
            style={{ textDecoration: "none" }}
          >
            <Card
              mih={320}
              shadow="md"
              w={300}
              withBorder
              style={{
                cursor: "pointer",
              }}
            >
              <Title order={3}>{post.title}</Title>
              <Text>{post.body}</Text>
              <Text c="blue" pt="md">
                Go to post
              </Text>
            </Card>
          </Link>
        ))}
      </Flex>
    </Stack>
  );
}

// apps/5.1-sveltekit-ssr/src/routes/+page.svelte
<script lang="ts">
  import { Alert, Card } from 'flowbite-svelte';
  import type { PageData } from './$types';

  export let data: PageData;
  const { posts, error } = data;
</script>

<div class="p-8">
  <h2 class="text-2xl font-bold mb-4">Your Home Feed</h2>
  <div class="flex flex-wrap gap-4">
    {#if error}
      <Alert color="red">
        <span class="font-medium">Bummer!</span>
        There was an error fetching posts
      </Alert>
    {:else}
      {#each posts as post (post.id)}
        <a href="/posts/{post.id}" class="no-underline">
          <Card class="w-72 h-80 cursor-pointer">
            <h3 class="text-xl font-bold mb-2">{post.title}</h3>
            <p class="mb-4">{post.body}</p>
            <p class="text-blue-600 mt-auto">Go to post</p>
          </Card>
        </a>
      {/each}
    {/if}
  </div>
</div>
